In [1]:
import os
import numpy as np
import pandas as pd
import json
from datetime import date, datetime, timedelta
from sklearn.preprocessing import MinMaxScaler

In [48]:
def minmax_scale(data, axis=1, min=None, max=None, feature_range=(0,1), reverse=False) -> np.array:
    '''
    Factor 지표에 대해서 스케일링 처리해줌
        - data : minmax 스케일링 할 데이터
        - axis : 스케일링을 적용할 축 
            - Factor 의 경우 가로축 데이터를 대상으로 할때는 axis=1)
        - scaler : 만약, trainset이 아닌경우에는 scaler 객체를 받아와서 적용한다.
    
    Output
        - scaled_data : 스케일링 적용이 완료된 데이터
        - data_min, data_max (np.array) : 민맥스 스케일링 정보 담은 리스트
    '''
    X = data
    feat_min, feat_max = feature_range

    if min==None and max==None:
        min = np.expand_dims(X.min(axis=axis), axis=axis)
        max = np.expand_dims(X.max(axis=axis), axis=axis)

    X_std = (X-min)/(max - min) 
    X_scaled = X_std*(feat_max-feat_min)+feat_min

    if reverse:
        X_scaled = feat_max-X_scaled
    
    # print("X_std: ", X_std)
    # print("X_std: ", X_scaled)
    return X_scaled # min, max

In [40]:
# data = np.array([i for i in range(200)]).reshape(20,10)
data = np.random.rand(5,3)
minmax_scale(data, axis=1)

[[0.03822811 0.04112065 0.        ]
 [0.         0.4980528  0.78781102]
 [0.42245564 0.         0.2545814 ]
 [0.         0.48721694 0.59464055]
 [0.         0.48118583 0.38371542]]


array([[0.92965727, 1.        , 0.        ],
       [0.        , 0.63219832, 1.        ],
       [1.        , 0.        , 0.6026228 ],
       [0.        , 0.81934698, 1.        ],
       [0.        , 1.        , 0.79743707]])

In [50]:
print(data)
minmax_scale(data, axis=1, reverse=True)

[[0.71120282 0.71409536 0.67297471]
 [0.06152607 0.55957887 0.84933709]
 [0.70582224 0.28336659 0.537948  ]
 [0.17268983 0.65990677 0.76733039]
 [0.43247865 0.91366448 0.81619407]]


array([[0.07034273, 0.        , 1.        ],
       [1.        , 0.36780168, 0.        ],
       [0.        , 1.        , 0.3973772 ],
       [1.        , 0.18065302, 0.        ],
       [1.        , 0.        , 0.20256293]])